### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pichalite** [psychobunny/templates.js#50]
Getting this error after updating to latest templates.js

`<a href="<!-- IF categories.link -->{categories.link}<!-- ELSE -->{config.relative_path}/category/{categories.slug}<!-- ENDIF categories.link-->" itemprop="url" <!-- IF categories.link -->target="_blank"<!-- ENDIF categories.link-->>`

`error: RangeError: Maximum call stack size exceeded
    at String.match (native)
    at checkConditional (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:221:26)
    at checkConditionals (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:217:27)
    at parseValue (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:383:14)
    at parse (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:402:17)
    at cleanup (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:473:27)
    at parse (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:419:15)
    at cleanup (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:473:27)
    at parse (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:419:15)
    at cleanup (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:473:27)
RangeError: Maximum call stack size exceeded
    at String.match (native)
    at checkConditional (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:221:26)
    at checkConditionals (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:217:27)
    at parseValue (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:383:14)
    at parse (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:402:17)
    at cleanup (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:473:27)
    at parse (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:419:15)
    at cleanup (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:473:27)
    at parse (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:419:15)
    at cleanup (/pathto/NodeBB/node_modules/templates.js/lib/templates.js:473:27)`

**Comment by psychobunny** [comment]
Hey latest tjs is unstable, I downgraded NodeBB to the previous version. That said, looks like you can rewrite the code to just use the one if statement? Don't close though, I'll have to look into this thanks

**Comment by psychobunny** [comment]
Oh I see the error;

`<!-- ENDIF categories.link-->`

Add a space at the end of link. Reasoning being we were waiting OP/s on validating syntax on each render, our plan is to eventually to parse in advanced and detect invalid syntax on compilation instead

**Comment by pichalite** [comment]
I see, thanks.
